# If your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would
# contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
baseURL: "https://cloudjur.com/"
title: Cloudjur
copyright: ""
paginate: 15
theme: [PaperMod]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# enableGitInfo: true
mainsections: ["blogs"]
hasCJKLanguage: true

minify:
  disableXML: true
  # minifyOutput: true

# permalinks:
#   blogs: "/:title/"

defaultContentLanguage: en
defaultContentLanguageInSubdir: true

menu:
  main:
    - identifier: search
      name: 🔍 Search
      url: search
      weight: 1
    - identifier: home
      name: 🏠 Home
      url: /
      weight: 2
    - identifier: blogs
      name: 📚 blogs
      url: blogs
      weight: 3
    - identifier: tags
      name: 🧩 Tags
      url: tags
      weight: 15
    - identifier: archives
      name: ⏱️ Archives
      url: archives/
      weight: 20
    - identifier: about
      name: 🙋🏻‍♂️ About Me
      url: about
      weight: 50
    - identifier: Wiki
      name: 🤝 Wiki
      url: wiki
      weight: 60


languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - identifier: search
          name: 🔍 Search
          url: search
          weight: 1
        - identifier: home
          name: 🏠 Home
          url: /
          weight: 2
        - identifier: blogs
          name: 📚 Blogs
          url: blogs
          weight: 3
        - identifier: tags
          name: 🧩 Tags
          url: tags
          weight: 15
        - identifier: archives
          name: ⏱️ Archives
          url: archives/
          weight: 20
        - identifier: about
          name: 🙋🏻‍♂️ About Me
          url: about
          weight: 50
        - identifier: Wiki
          name: 🤝 Wiki
          url: https://wiki.cloudjur.com
          weight: 60

    # custom params for each language should be under [langcode].parms - hugo v0.120.0
    params:
      languageAltTitle: English
      profileMode:
        enabled: true
        title: Jun Kin
        imageUrl: "https://raw.githubusercontent.com/googlefonts/noto-emoji/master/svg/emoji_u1f9d1_1f3fb_200d_1f4bb.svg"
        imageTitle: Profile Icons
        # imageWidth: 120
        # imageHeight: 120
        subtitle: "😎 Tech Nerd"
        buttons:
          - name: Blogs
            url: blogs
          - name: Profile Mode
            url: https://github.com/chaijunkin/home/about

  # fa:
  #   languagedirection: rtl
  #   weight: 3
  #   title: PaperMod RTL
  #   taxonomies:
  #     category: FAcategories
  #     tag: FAtags
  #     series: FAseries
  #   menu:
  #     main:
  #       - name: FATags
  #         url: fatags
  #         weight: 10
  #   # custom params for each language should be under [langcode].parms - hugo v0.120.0
  #   params:
  #     homeInfoParams:
  #       Title: "Hi there \U0001F44B"
  #       Content: Welcome to RTL layout

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Cloudjur"
  author: Jun Kin
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideFooter: false
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true

  profileMode:
    enabled: true
    title: Cloudjur
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Cloudjur"
    Content:
      Intro: I'm Jun Kin, and welcome to my *cloud*.
      About: I write about my work and life as an open source contributor/maintainer and an amateur
      Action: If you're here for the first time, try my [featured blogs](/categories/featured/) or learn more [about me](/about). Make sure to subscribe via [email](/subscribe) or [RSS](/index.xml) to get regular updates.

    subscribeInfo:
      Text: If you liked this post, check out my [featured blogs](/categories/featured) or learn more [about me](/about).


  socialIcons:
    - name: email
      url: "mailto:chaijunkin@gmail.com"
    - name: github
      title: View Source on Github
      url: "https://github.com/chaijunkin"
    - name: youtube
      title: Youtube video
      url: "https://youtube.com/@chaijunkin_ch"
    - name: Discord
      title: My Discord
      url: "https://discordapp.com/users/386723201830354946"
    - name: X
      title: Contact me via X!
      url: "https://twitter.com/chaijunkin"
    - name: Linkedin
      title: Contact me via "https://www.linkedin.com/in/chaijunkin"!
      url: "https://www.linkedin.com/in/chaijunkin"
    - name: KoFi
      title: Buy me a Ko-Fi :)
      url: "https://ko-fi.com/junkin"
    - name: rss
      url: /index.xml

  editPost:
    URL: "https://github.com/chaijunkin"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # label:
  # iconSVG: '<svg xmlns="http://www.w3.org/2000/svg" height="25" viewBox="0 -960 960 960" fill="currentColor"><path d="M320-240h320v-80H320v80Zm0-160h320v-80H320v80ZM240-80q-33 0-56.5-23.5T160-160v-640q0-33 23.5-56.5T240-880h320l240 240v480q0 33-23.5 56.5T720-80H240Zm280-520v-200H240v640h480v-440H520ZM240-800v200-200 640-640Z"/></svg>'
  # text: "Jun Kin's Blogs"
  # icon: icon.png
  # iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  assets:
    disableHLJS: true
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  cover:
      hidden: false # hide everywhere but not in structured data
      hiddenInList: false # hide on list pages and home
      hiddenInSingle: false # hide on single page

  fuseOpts:
      isCaseSensitive: false
      shouldSort: true
      location: 0
      distance: 1000
      threshold: 0.4
      minMatchCharLength: 0
      keys: ["title", "permalink", "summary", "content"]

  StartYear: 2024
  # FilingNo: 
  # PublicSecurityIconLink: 
  # PublicNetworkSecurity: 

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    # lineNos: true
    tabWidth: 4
    style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true